require("yongde.plugins-setup")
require("yongde.core.options")
require("yongde.core.keymaps")
require("yongde.core.colorscheme")
require("yongde.plugins.comment")
require("yongde.plugins.nvim-tree")
require("yongde.plugins.lualine")
require("yongde.plugins.telescope")
require("yongde.plugins.nvim-cmp")
require("yongde.plugins.lsp.mason")
require("yongde.plugins.lsp.lspsaga")
require("yongde.plugins.lsp.lspconfig")
require("yongde.plugins.lsp.null-ls")
require("yongde.plugins.autopairs")
require("yongde.plugins.treesitter")
require("yongde.plugins.gitsigns")

-- 更改vim-tmux-navigator的快捷鍵
vim.g.tmux_navigator_no_mappings = 1
vim.api.nvim_set_keymap("n", "<C-n>", "<cmd>TmuxNavigateLeft<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-m>", "<cmd>TmuxNavigateDown<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-,>", "<cmd>TmuxNavigateUp<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-.>", "<cmd>TmuxNavigateRight<CR>", { noremap = true, silent = true })
